server.port: 8080
spring.application.name: server

spring.datasource:
  url: "jdbc:h2:file:./yaff-h2"
  username:
  password:
spring.jpa.hibernate.ddl-auto: update

springdoc:
  swagger-ui:
    enabled: true
    path: /dev/swagger-ui/index.html
    url: /dev/api-docs.yaml
  api-docs:
    enabled: true
    path: /dev/api-docs.yaml



management.endpoints.web.exposure.include: "*"