server:
  port: 8080
  host: 0.0.0.0
app:
    greeting: "Hello"

jackson:


db:
  source: "jdbc"
  connection:
    url: "jdbc:h2:./demo-db"

  statements:
    ping: "DO 0"
    select-all-pokemons: "SELECT id, name FROM Pokemons"